crate/cratedb-prometheus-adapter

- server.go
Whenever a query requires more than 10s the crate_adapter triggers a `context deadline exceeded`
Since a lot of queries might require more than 10 seconds to execute (especially when querying a large amount of data) I increased the default timeout to 1m, consistently with the `remote_read` timeout of prometheus ( https://github.com/prometheus/prometheus/blob/master/config/config.go#L130 )
In the future it probably make sense to make this timeout configurable.
> Increase timeout for requests

- server.go
Reads were being observed to writeSamples instead of readSamples
> Fixed incorrect sample summary reference

- server.go
According to the [documentation](https://crate.io/docs/crate/reference/en/latest/general/dql/selects.html#regular-expressions) CrateDB regular expressions are implicitly anchored, so no need for an explicit anchor in the adapter queries - doing so produces an empty result set from CrateDB.
Original code, returns no data:
```
SELECT labels, labels_hash, timestamp, value, "valueRaw" FROM prometheus.metrics WHERE (labels['container_name'] ~ '^(?:crate|prometheus)$') AND (labels['__name__'] = 'container_cpu_usage_seconds_total') AND (timestamp <= 1551782847341) AND (timestamp >= 1551782547341) ORDER BY timestamp limit 100;
```
As per pull request, returns data:
```
SELECT labels, labels_hash, timestamp, value, "valueRaw" FROM prometheus.metrics WHERE (labels['container_name'] ~ …
```
> Fix regular expression handling

- server.go
I missed updating this log message when converting the adapter from HTTP
to Postgres protocol back then in 2018.
Signed-off-by: Julius Volz <julius.volz@gmail.com>
The current log message is misleading / incorrect / outdated, since the adapter no longer speaks HTTP to CrateDB.
> Fix old log message mentioning POST method

- README.rst
- config.yml
The `config.yaml` should provide defaults that work with CrateDB defaults.
> Provide usable defaults in config.yaml

- .github/workflows/tests.yml
- .gitignore
- CHANGES.rst
- DEVELOP.rst
- Dockerfile
- README.rst
- devtools/create_tag.sh
- go.mod
- server.go
- server_test.go
- systemd/crate_adapter.default
- systemd/cratedb-prometheus-adapter.default
- systemd/cratedb-prometheus-adapter.service
Hi there,
as this codebase was getting some love by @chaudum recently (thanks a stack!), I decided to finally propose using a more appropriate name for this repository and its contents. I believe `crate_adapter` gives way too little context what it is all about. Before this will reach a 1.0.0, I believe it is a sensible thing to do.
This patch renames the program to be called `cratedb-prometheus-adapter`. Also, by default, it now uses `cratedb_prometheus_adapter_` as a prefix for the metrics it exports itself. However, this can be configured like `./cratedb-prometheus-adapter -metrics.export.prefix=crate_adapter_` to use the former metrics prefix.
Andreas.
> Naming things, use "cratedb-prometheus-adapter"

- .github/workflows/release.yml
- Dockerfile
- README.rst
Hi there,
this adds a recipe derived from [1] to the CI configuration. It should build and publish Docker images when there are tags pushed to the repository.
Andreas.
[1] https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
> Automatically release Docker images to GHCR

- CHANGES.rst
- README.rst
- config.yml
- fixtures/config_good.yml
- fixtures/config_no_endpoints.yml
- fixtures/config_unknown_fields.yml
- server.go
Hi again,
this accompanies the "naming things" patch coming from #40.
Andreas.
> Rename toplevel configuration section name to "cratedb_endpoints"

- DEVELOP.rst
- README.rst
- systemd/cratedb-prometheus-adapter.default
Hi there,
accompanying our previous improvements, this finally gives some love to the documentation (README file).
It moves all developer-related information to the "DEVELOP.rst" file and better outlines how to use the release archives and images within "README.rst".
Andreas.
> Improve documentation

- .github/workflows/release.yml
Aims to fix running the "Release" job interactively [^1]. Now, it succeeded at [^2], by omitting the "push" step in this case.
[^1]: https://github.com/crate/cratedb-prometheus-adapter/actions/runs/3940882765/jobs/6742554727#step:10:136
[^2]: https://github.com/crate/cratedb-prometheus-adapter/actions/runs/3940965430/jobs/6742744601
> CI: Don't push image to ghcr.io when "Release" job runs interactively

- CHANGES.rst
- DEVELOP.rst
- README.rst
- server.go
- server_test.go
Hi there,
this patch aims to address GH-49. It implements three things.
- Accept invocation without default configuration file `config.yml`: When running `./cratedb-prometheus-adapter`, and there is no `config.yml` file in the working directory, the built-in default settings will be used, see https://github.com/crate/cratedb-prometheus-adapter/blob/75811a33de7dd823cc458365b7f2f2bd234b5c9c/server.go#L376-L392
- Add command line option `-config.make` to print a blueprint configuration file to stdout. It can be used like
```
./cratedb-prometheus-adapter -config.make > config.yml
```
- Add program version to startup log message
Andreas.
/cc @chaudum
> Improve (first-time) invocation convenience

- README.rst
Hi there,
this patch pulls in the improved documentation section from [^1] about how to invoke the service using systemd.
Andreas.
[^1]: https://community.crate.io/t/cratedb-prometheus-adapter-service-not-starting/971/7
/cc @brians
> README: Improve systemd documentation

- CHANGES.rst
- DEVELOP.rst
- README.rst
- server.go
- server_test.go
Hi again,
GH-59 was not solid enough.
1. It introduced a flaw that the program stopped failing when `-config.path` pointed to a non-existing path, and also used the built-in settings instead. This is wrong, the program should croak in this case.
2. Also, `-config.make` did not work as intended yet. It printed an _empty_ configuration, instead of the built-in default settings.
```
$ docker run -it --rm --publish=9268:9268 ghcr.io/crate/cratedb-prometheus-adapter:nightly -config.make
WARN[0000] No configuration file "config.yml": open : no such file or directory  source="server.go:368"
INFO[0000] Falling back to default configuration         source="server.go:369"
cratedb_endpoints:
- host: ""
port: 0
user: ""
password: ""
schema: ""
enable_tls: false
allow_insecure_tls: false …
```
> Fix invocation behavior

- .github/dependabot.yml
- .github/workflows/tests.yml
- CHANGES.rst
- go.mod
- Add support for Go 1.20 and 1.21, drop support for previous releases.
Go 1.18 and 1.19 are end-of-life, see https://endoflife.date/go.
- CI: Support running software tests on stacked pull requests.
- CI: Also check GitHub Action dependencies.
- CI: Update to actions/setup-go@v4.
> Maintenance: Update Go versions and CI configuration

- CHANGES.rst
- crate.go
- crate_test.go
- server.go
At https://github.com/crate/cratedb-prometheus-adapter/pull/77#discussion_r1311560136, @hlcianfagna reported that it may not be a good idea to converge to connection strings in URL format. This patch switches over to use DSN-style connection strings.
> Use DSN-style connection strings

- CHANGES.rst
- go.mod
- server.go
Update to `google.golang.org/protobuf 1.31`. See also:
- GH-62
> Update Protocol Buffers libraries

- crate.go
Update to write function to work with pgx4
Closes: #88
> Update to write function to work with pgx4 and higher

- .github/dependabot.yml
- .github/workflows/tests.yml
- .gitignore
- DEVELOP.rst
- README.rst
- crate.go
- pyproject.toml
- requirements-test.txt
- server.go
- sql/ddl.sql
- tests/conftest.py
- tests/docker-compose.yaml
- tests/prometheus.yml
- tests/test_adapter.py
- tests/test_prometheus.py
As we learned through GH-88, the unit tests are not sufficient to validate the code base thoroughly. This patch intends to bring in integration tests with real instances of Prometheus, CrateDB, and CrateDB Prometheus Adapter, effectively adding end-to-end test cases, so that corresponding required adjustments/fixes like GH-96 or 2043818d will not be missed in the future.
The patch also includes the commit 2043818d20, which is actual a bugfix accompanying GH-96. It has been discovered while adding the test cases validating the read path.
The integration tests added on behalf of this patch will ensure that bringing in those upcoming dependency update patches will not break the application again.
- GH-98
- GH-102
- GH-103
- GH-108
/cc @matriv, @seut, @ckurze, @wierdvanderhaar
> Add integration tests

- CHANGES.rst
- server.go
Preparing new release following the template from https://github.com/crate/cratedb-prometheus-adapter/pull/48
> Release 0.5.0

- .dockerignore
- .github/workflows/builds.yml
- .github/workflows/oci.yml
- Dockerfile
- devtools/release.Dockerfile
- devtools/release.sh
While OCI images for 0.5.0 have been released, the binary program builds failed. This patch resolves GH-111, and adds a corresponding GHA CI workflow to ensure they don't break again unnoticed.
> CI: Fix broken build by using most recent Golang version (1.21)

- .github/workflows/builds.yml
- devtools/release_build.sh
Add build slots for ARMv8 (64-bit) for all of Linux, Darwin, and Windows. Also add ARMv7 (32-bit) for Linux.
> CI: Start building binaries for the ARM architecture

- .github/workflows/oci.yml
Following the spirit of GH-113, this patch also adds the ARM architecture to OCI builds. OCI images are Linux-only so far.
> CI: Start providing OCI images for the ARM architecture

- tests/test_expressions.py
Mostly in order to check the situation with GH-24, this patch adds a few more integration test cases to verify a collection of query expressions end-to-end.
> Tests: Integration tests to verify query expressions end-to-end

- DEVELOP.rst
- backlog.md
- pyproject.toml
- sandbox/docker-compose.yaml
- sandbox/prometheus.yml
- sandbox/promquery.py
- tests/conftest.py
- tests/prometheus.yml
- tests/test_adapter.py
- Sandbox: Add development sandbox Docker Compose configuration
- Tests: Fix PROMETHEUS_URL: No trailing slash, otherwise lots of 301
- Tests: For unknown reasons so far, `test_verify_read_activity` now fails
on developer workstation
- Tests: Adjust `subsystem` label within Prometheus configuration
- Chore: Update backlog
> Chore: Development sandbox Docker Compose configuration; Tests: Fix `PROMETHEUS_URL`; deactivate failing test; Misc.

- CHANGES.rst
- crate.go
- pyproject.toml
- tests/conftest.py
- tests/cpa-config.yml
- tests/test_adapter.py
The `schema` configuration setting was not honored. This patch intends to fix that flaw.
> Fix use of `schema` configuration setting, it was not honored

- CHANGES.rst
- crate.go
Considering that Prometheus doesn't allow samples with same timestamp and different values and enforcing this more strictly with newer version, just adding a `ON CONFLICT DO NOTHING` should be sufficient.
> Ignore samples with different values with same timestamp on ingest

- crate.go
Investigating this issue https://github.com/crate/cratedb-prometheus-adapter/issues/176, I found that the connection pool is created on every request, and the previous pool is not explicitly closed.
> chore: remove creation of new pool on every request which can lead to potential memory leak

- .github/workflows/tests.yml
- CHANGES.rst
- Dockerfile
- devtools/release.Dockerfile
Use [Golang 1.24](https://go.dev/doc/go1.24) across the board.
go1.24.0 has been released on 2025-02-11.
go1.24.1 has been released on 2025-03-04.
> OCI: Update images to use Golang 1.24
